### ISSUE TITLE
Non-ASCII character in .py, no encoding declared

### ISSUE THREAD

**Issue by greenkidneybean** [snakemake-workflows/dna-seq-gatk-variant-calling#10]
When running `snakemake --use-conda` from the project root of the project directory I get the following error (line 43 of attached 
[snakemake.log](https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling/files/3263287/snakemake.log)):

```
SyntaxError: Non-ASCII character '\xc3' in file /spin1/users/chambersmj/snakemake_test/.snakemake/scripts/tmpmfjaxtfh.wrapper.py on line 5, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

I thought of adding `#coding=utf-8` to the head of .snakemake/scripts/tmpmfjaxtfh.wrapper.py but there are no scripts in the .snakemake/scripts directory.

Any suggestions to resolve the python source file encoding would be greatly appreciated :blush:

Note: I've also attached the default [config.yaml](https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling/files/3263311/config.txt), the project tree is below, and the data directory was cloned from  [snakemake-workflows/ngs-test-data](https://github.com/snakemake-workflows/ngs-test-data).

```
snakemake_test
├── config.txt
├── config.yaml
├── data
├── envs
├── LICENSE
├── logs
├── mapped
├── README.md
├── report
├── rules
├── samples.tsv
├── schemas
├── scripts
├── Snakefile
├── snakemake.log
├── trimmed
└── units.tsv
```

**Comment by greenkidneybean** [comment]
This issue has been resolved.

tmux was pointing Python to the system version (2.7) and not my conda environment (3.6).  Still not sure why tmux points to a different python version as opposed to when I'm detached from a session.  Cheers!

**Comment by johanneskoester** [comment]
No idea, I use tmux all the time. Maybe an issue with your shell configuration?

**Comment by greenkidneybean** [comment]
Starting a tmux session appended a few directories to my path, which was surpassing the conda path.  I added the following line to my .tmux.conf to fix: `set -g default-command "${SHELL}"`
