### ISSUE TITLE
Erro in rule snpeff

### ISSUE THREAD

**Issue by greenkidneybean** [snakemake-workflows/dna-seq-gatk-variant-calling#11]
Having trouble with the annotation rule snpeff and have attached the [snpeff.log](https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling/files/3267658/snpeff.log).  I'm confused as to why the connection to sourceforge is necessary, but the link in the log file is valid and not sure why it's not downloading.

**Comment by johanneskoester** [comment]
SnpEff downloads an annotation database on the first run. If you have a working internet connection, maybe there was a temporal downtime of the snpeff servers? Please reopen if you think this is a problem of this particular workflow.
